### ISSUE TITLE
Hello from app.js conf!

### ISSUE THREAD

**Issue by kacgrzes** [showtime-xyz/showtime-frontend#1163]

**Comment by izakfilmalter** [comment]
FINALLY

**Comment by enesozturk** [comment]
Yoo guys, welcome! ✨

**Comment by Janak-Nirmal** [comment]
Any blog published for how are you managing mono repo ? step by step ? Loving this. Thanks.

**Comment by enesozturk** [comment]
Hi @Janak-Nirmal 🤞🏽, we don't have any blog post and detailed documentation about that but Readme's would help. You can find many details (folder structure, scripts, notes, etc.) in [packages/app/readme.md](https://github.com/showtime-xyz/showtime-frontend/tree/staging/packages/app)

**Comment by axeldelafosse** [comment]
Context: https://twitter.com/axeldelafosse/status/1541397025194909699.

Closing this now, feel free to open a discussion if you want to connect! Cheers!
