### ISSUE TITLE
Coinbase logo do not load on the website

### ISSUE THREAD

**Issue by flexbox** [showtime-xyz/showtime-frontend#1166]
from https://showtime.xyz/trending

As a user 
I can sign in with my coinbase wallet

**Expected**
Display the coinbase logo

**Reality**
<img width="899" alt="image" src="https://user-images.githubusercontent.com/360936/173187170-2d1ffd93-3eea-4301-b386-882b1dcd6b6e.png">

The coinbase is not properly loaded
<img width="472" alt="image" src="https://user-images.githubusercontent.com/360936/173187148-8e27a0a7-2fc4-433d-a8d0-b37b884f688a.png">

**Comment by alantoa** [comment]
Hey, @flexbox! 👋
Thanks for your feedback!
We know this issue, in the next web version we will use [Rainbowkit](https://github.com/rainbow-me/rainbowkit) to log in, and will fix this, you can see in the [code](https://github.com/showtime-xyz/showtime-frontend/blob/staging/packages/app/providers/wallet-provider.web.tsx)!
It's done by @enesozturk  and we'll be releasing it soon! 🚀

**Comment by dbcxx** [comment]
never knew about [Rainbowkit ](https://github.com/rainbow-me/rainbowkit)I still have alot to learn :worried:

**Comment by alantoa** [comment]
hey, @dbcxx!
haha, no worries, Rainbowkit is a recently released wallet connect tool!
for web3, I'm a noob too, but it's not rocket science, keep learning and communicating, you can do it!

**Comment by flexbox** [comment]
Thank @alantoa for the link 
it looks nice!
