### ISSUE TITLE
Cannot convert undefined or null to object, in push notifications under settings

### ISSUE THREAD

**Issue by distroinfinity** [showtime-xyz/showtime-frontend#1666]
Hey there the following errors pops up when I try to navigate to the push notifications section through my profile. Not sure if this has to be this way, sorry for opening the issue if this was intentional. 

<img width="1430" alt="image" src="https://user-images.githubusercontent.com/59890794/199221993-ae72a978-bfbc-4ad7-a320-a43988c39910.png">

**Comment by alantoa** [comment]
hey @distroinfinity! thanks for your feedback!
is it on prod or dev? does everything work fine on native?

**Comment by distroinfinity** [comment]
Hey @alantoa its in prod, i am using it on the browser(tried on brave and chrome), haven't used the native apps. The error pops up on this route specifically https://showtime.xyz/settings?tab=4

**Comment by alantoa** [comment]
oh, I got it, looking into this, @distroinfinity thank you!

**Comment by alantoa** [comment]
fixed in https://github.com/showtime-xyz/showtime-frontend/pull/1669 , and deploying.
thank you very much for this feedback! @distroinfinity 🙏
