### ISSUE TITLE
Getting blank screen after successful build 

### ISSUE THREAD

**Issue by mmuhd** [showtime-xyz/showtime-frontend#1692]
Hi, thank you for this amazing project, I wanted to learn a thing or two about web3 development, I stumbled upon this repo.
I am building it successfully using yarn android -d and getting blank black screen on the connected device. Anything I might be doing wrong? Thanks again.

**Comment by alantoa** [comment]
hey, @mmuhd thanks for your feedback! 

 
- can you make sure `yarn start` is running and then open the app again? 
- and can you make sure the app connects to your expo development server and make sure the domain and port are correct?

if make sure is correct above and still not working, can your share a video with me, happy to dig it!

**Comment by mmuhd** [comment]
Hey @alantoa Thank  you for the reply, 
I will try the above and revert thank you once again.

**Comment by mmuhd** [comment]
Yes got it working Thank you @alantoa
