### ISSUE TITLE
ERROR TypeError: undefined is not an object (evaluating '_NativeWindStyleSheet.create')

### ISSUE THREAD

**Issue by michaelmowry** [showtime-xyz/showtime-frontend#1759]
1. Followed the Getting Started steps here - https://axeldelafosse.com/blog/universal-design-system
2. Ran yarn native
3. Got the error above

Any ideas on what I missed or how to fix?

**Comment by alantoa** [comment]
hey @michaelmowry, I want to help you, looks like your setup is not our project,  can you share with me the project link?
