### ISSUE TITLE
Is there any backend API documentation

### ISSUE THREAD

**Issue by Osub** [showtime-xyz/showtime-frontend#1936]

**Comment by hirbod** [comment]
The backend is closed source unfortunately.

**Comment by johndpope** [comment]
Let's start something (I have some backend code from a nextjs + supabase project that I can bring to table) 
- this repo is of no use without a backend - not necessarily the backend 

I have no intentions to do nfts / sales - but I love the feeds / commenting - the sign in flow and would love help. 
let's discuss here - https://github.com/johndpope/showtime-backend/issues/1
