### ISSUE TITLE
Reading `sessionStorage` on every render

### ISSUE THREAD

**Issue by nandorojo** [showtime-xyz/showtime-frontend#2450]
https://github.com/showtime-xyz/showtime-frontend/blob/c15e7af2eee3bd73828744ff28dd2d42ad52a54b/packages/design-system/infinite-scroll-list/infinite-scroll-list.web.tsx#L100

This code is reading `sessionStorage` on every render when `preserveScrollPosition` is true fyi. Not ideal for performance.

**Comment by hirbod** [comment]
@nandorojo what you think about this?
https://github.com/showtime-xyz/showtime-frontend/pull/2451

Just made some tests and this prevents the excessive calls. Also made sure to write only to the storage when the browser is idle (on top of the debounce).
